export const nativeStart: () => void;
export const nativeStop: () => void;
export const nativeStartIfForeground: () => void;
export const nativeSetModelAssets: (player: ArrayBuffer, enemy: ArrayBuffer, boss: ArrayBuffer) => boolean;
export const nativeSetEnvironmentAssets: (outer: ArrayBuffer, center: ArrayBuffer,
  backdrop: ArrayBuffer, decoration: ArrayBuffer) => boolean;
export const nativeSetBlockAsset: (blockId: number, bytes: ArrayBuffer) => boolean;
export const nativeSetNpcAsset: (bytes: ArrayBuffer) => boolean;
// 敌人原型独立模型槽位（独立高模资产）：archetype ∈ [0, 6)，
// 缺失时 native 侧保持共享 enemy.glb 回退。
export const nativeSetEnemyArchetypeAsset: (archetype: number, bytes: ArrayBuffer) => boolean;
export const pushInput: (event: {type: number, pointerId: number, x: number, y: number}) => void;
export const pushAction: (type: number) => void;
export const startEncounter: (mode: number) => boolean;
export const advanceLevel: () => boolean;
export const useSupply: () => boolean;
export const retryBoss: () => boolean;
export const toggleDebugHud: () => void;
export const advanceDialog: () => void;
export const saveProgress: (path: string) => boolean;
export const loadProgress: (path: string) => boolean;
export const performGacha: (count: number) => boolean;
export const performWeaponGacha: (count: number) => boolean;
export const useExpMaterial: (characterId: number, materialCount: number) => boolean;
export const ascendCharacter: (characterId: number) => boolean;
export const upgradeWeapon: (weaponId: number) => boolean;
export const equipWeapon: (weaponId: number, characterId: number) => boolean;
export const upgradeWeaponWithOre: (weaponId: number, oreItemId: number, count: number) => boolean;
export const ascendWeapon: (weaponId: number) => boolean;
export const refineWeapon: (weaponId: number) => boolean;
export const useExpItem: (characterId: number, itemId: number, count: number) => boolean;
export const upgradeArtifact: (targetInstanceId: number, feedInstanceIds: number[]) => boolean;
export const equipArtifact: (instanceId: number, characterId: number) => boolean;
export const claimRankReward: (rank: number) => boolean;
export const setQualityPreset: (preset: number) => void;
export const teleportToAnchor: (anchorId: number) => boolean;
export const setAudioEnabled: (enabled: boolean) => void;
export const setPaused: (paused: boolean) => void;
export const skipDemoPhase: (phase: number) => void;
export const pullSnapshot: () => {
  tick: number,
  hp: number,
  poise: number,
  x: number,
  y: number,
  fps: number,
  moving: boolean,
  moveX: number,
  moveY: number,
  cameraYaw: number,
  cameraPitch: number,
  targetDist: number,
  targetArchetype: number,
  targetHpRatio: number,
  targetId: number,
  bossPhase: number,
  encounterMode: number,
  encounterState: number,
  rendererReady: boolean,
  environmentReady: boolean,
  environmentDrawCalls: number,
  environmentTriangles: number,
  stamina: number,
  comboSegment: number,
  invulnerable: boolean,
  insightMs: number,
  resonance: number,
  targetHp: number,
  targetPoise: number,
  pulseHitRemainingMs: number,
  lastRejectReason: number,
  currentAction: number,
  comboWindowMs: number,
  radianceCooldownMs: number,
  currentCooldownMs: number,
  corruptionCooldownMs: number,
  radianceCooldownTotalMs: number,
  currentCooldownTotalMs: number,
  corruptionCooldownTotalMs: number,
  ultimateWindowMs: number,
  targetPoiseBroken: boolean,
  radianceAttached: boolean,
  currentAttached: boolean,
  corruptionAttached: boolean,
  corroded: boolean,
  currentReaction: number,
  pulsePhase: number,
  levelStage: number,
  gateState: number,
  supplyState: number,
  bossHp: number,
  bossPoise: number,
  bossMechanic: number,
  bossCastMs: number,
  perfLevel: number,
  vfxFlags: number,
  cameraShakeX: number,
  cameraShakeY: number,
  bossHpRatio: number,
  bossCastRatio: number,
  debugHud: boolean,
  objectiveLabel: string,
  resonanceSlots: number[],
  showDebugHud: boolean,
  bossCinematicProgress: number,
  bossShardCount: number,
  bossSourceColor: number,
  bossRingBroken: boolean,
  inputEventCount: number,
  explorationStamina: number,
  motionState: number,
  playerHeight: number,
  activeChunkCount: number,
  chunkLoadCount: number,
  interactionAnchorId: number,
  interactionUnlocked: boolean,
  interactionLabel: string,
  unlockedAnchorCount: number,
  cameraExploration: boolean,
  teleportFlashMs: number,
  minimapAnchorX: number[],
  minimapAnchorY: number[],
  minimapAnchorUnlocked: number[],
  questId: number,
  questStatus: number,
  questTitle: string,
  questObjectiveLabel: string,
  questObjectiveProgress: number,
  questObjectiveRequired: number,
  completedQuestCount: number,
  dialogActive: boolean,
  dialogSpeaker: string,
  dialogText: string,
  dialogLineIndex: number,
  dialogLineCount: number,
  interactionKind: number,
  fateCount: number,
  goldCount: number,
  expMaterialCount: number,
  ascensionMaterialCount: number,
  gachaPity5: number,
  gachaResultIds: number[],
  gachaResultRarities: number[],
  gachaResultIsNew: number[],
  rosterIds: number[],
  rosterLevels: number[],
  rosterAscensions: number[],
  activeCharacterId: number,
  dayNightHour: number,
  qualityPreset: number,
  weatherId: number,
  musicRegionId: number,
  completedSideQuestCount: number,
  dungeonState: number,
  dungeonProgress: number,
  dungeonRequired: number,
  minimapItemX: number[],
  minimapItemY: number[],
  minimapItemKind: number[],
  sideQuestProgress: number[],
  sideQuestRequired: number[],
  rosterHp: number[],
  rosterAtk: number[],
  rosterConstellations: number[],
  weaponIds: number[],
  weaponLevels: number[],
  weaponEquippedBy: number[],
  weaponAscensions: number[],
  weaponRefines: number[],
  weaponRefineStocks: number[],
  weaponExps: number[],
  artifactInstanceIds: number[],
  artifactDefIds: number[],
  artifactRarities: number[],
  artifactLevels: number[],
  artifactEquippedBy: number[],
  artifactSeeds: number[],
  adventureRank: number,
  adventureExp: number,
  adventureExpRequired: number,
  worldLevel: number,
  oreLowCount: number,
  oreMidCount: number,
  oreHighCount: number,
  expSmallCount: number,
  expMediumCount: number,
  expLargeCount: number,
  sprintActive: number,
  dailyCompletedCount: number,
  dailyQuestClaimed: number,
  gachaPoolKind: number,
  npcOfferQuestId: number,
  npcOfferQuestTitle: string,
  explorationPoiCount: number,
  explorationPuzzleCount: number,
  explorationRewardCount: number,
  explorationGateCount: number,
  explorationTraversalMask: number,
  explorationCurrentPoiId: number,
  explorationCurrentTargetLabel: string,
  explorationCurrentTargetDistrict: string,
  explorationBlockedGateId: number,
  explorationBlockedGateLabel: string,
  explorationBlockedByPuzzleLabel: string,
  explorationFeedbackType: number,
  explorationFeedbackId: number,
  explorationFeedbackTitle: string,
  explorationFeedbackSubtitle: string,
  explorationFeedbackRemainingMs: number,
};
